(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.errors.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.github_com.mit_pdos.perennial.goose.testdata.examples.channel.unbounded.

Set Default Proof Using "Type".

Module unbounded.
Module Unbounded.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : unbounded.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Unbounded_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (unbounded.Unbounded.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "c" ∷ l.[(unbounded.Unbounded.t), "c"] ↦{dq} v.(unbounded.Unbounded.c') ∗
      "closed" ∷ l.[(unbounded.Unbounded.t), "closed"] ↦{dq} v.(unbounded.Unbounded.closed') ∗
      "closing" ∷ l.[(unbounded.Unbounded.t), "closing"] ↦{dq} v.(unbounded.Unbounded.closing') ∗
      "mu" ∷ l.[(unbounded.Unbounded.t), "mu"] ↦{dq} v.(unbounded.Unbounded.mu') ∗
      "backlog" ∷ l.[(unbounded.Unbounded.t), "backlog"] ↦{dq} v.(unbounded.Unbounded.backlog') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Unbounded_into_val_typed
   :
  IntoValTypedUnderlying (unbounded.Unbounded.t) (unbounded.Unboundedⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Unbounded_access_load_c l (v : (unbounded.Unbounded.t)) dq :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "c"] ↦{dq} (v.(unbounded.Unbounded.c')))
    (l.[(unbounded.Unbounded.t), "c"] ↦{dq} (v.(unbounded.Unbounded.c')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Unbounded_access_store_c l (v : (unbounded.Unbounded.t)) c' :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "c"] ↦ (v.(unbounded.Unbounded.c')))
    (l.[(unbounded.Unbounded.t), "c"] ↦ c')
    (l ↦ v) (l ↦ (v <|(unbounded.Unbounded.c') := c'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Unbounded_access_load_closed l (v : (unbounded.Unbounded.t)) dq :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "closed"] ↦{dq} (v.(unbounded.Unbounded.closed')))
    (l.[(unbounded.Unbounded.t), "closed"] ↦{dq} (v.(unbounded.Unbounded.closed')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Unbounded_access_store_closed l (v : (unbounded.Unbounded.t)) closed' :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "closed"] ↦ (v.(unbounded.Unbounded.closed')))
    (l.[(unbounded.Unbounded.t), "closed"] ↦ closed')
    (l ↦ v) (l ↦ (v <|(unbounded.Unbounded.closed') := closed'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Unbounded_access_load_closing l (v : (unbounded.Unbounded.t)) dq :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "closing"] ↦{dq} (v.(unbounded.Unbounded.closing')))
    (l.[(unbounded.Unbounded.t), "closing"] ↦{dq} (v.(unbounded.Unbounded.closing')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Unbounded_access_store_closing l (v : (unbounded.Unbounded.t)) closing' :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "closing"] ↦ (v.(unbounded.Unbounded.closing')))
    (l.[(unbounded.Unbounded.t), "closing"] ↦ closing')
    (l ↦ v) (l ↦ (v <|(unbounded.Unbounded.closing') := closing'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Unbounded_access_load_mu l (v : (unbounded.Unbounded.t)) dq :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "mu"] ↦{dq} (v.(unbounded.Unbounded.mu')))
    (l.[(unbounded.Unbounded.t), "mu"] ↦{dq} (v.(unbounded.Unbounded.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Unbounded_access_store_mu l (v : (unbounded.Unbounded.t)) mu' :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "mu"] ↦ (v.(unbounded.Unbounded.mu')))
    (l.[(unbounded.Unbounded.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(unbounded.Unbounded.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Unbounded_access_load_backlog l (v : (unbounded.Unbounded.t)) dq :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "backlog"] ↦{dq} (v.(unbounded.Unbounded.backlog')))
    (l.[(unbounded.Unbounded.t), "backlog"] ↦{dq} (v.(unbounded.Unbounded.backlog')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Unbounded_access_store_backlog l (v : (unbounded.Unbounded.t)) backlog' :
  AccessStrict
    (l.[(unbounded.Unbounded.t), "backlog"] ↦ (v.(unbounded.Unbounded.backlog')))
    (l.[(unbounded.Unbounded.t), "backlog"] ↦ backlog')
    (l ↦ v) (l ↦ (v <|(unbounded.Unbounded.backlog') := backlog'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Unbounded.

End unbounded.
