(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.github_com.goose_lang.goose.testdata.examples.channel.map_reduce.leaky_buffer.

Set Default Proof Using "Type".

Module leakbuffer.
Module LeakyBuffer.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : leakbuffer.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance LeakyBuffer_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (leakbuffer.LeakyBuffer.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "serverChan" ∷ l.[(leakbuffer.LeakyBuffer.t), "serverChan"] ↦{dq} v.(leakbuffer.LeakyBuffer.serverChan') ∗
      "free" ∷ l.[(leakbuffer.LeakyBuffer.t), "free"] ↦{dq} v.(leakbuffer.LeakyBuffer.free') ∗
      "bufCap" ∷ l.[(leakbuffer.LeakyBuffer.t), "bufCap"] ↦{dq} v.(leakbuffer.LeakyBuffer.bufCap') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance LeakyBuffer_into_val_typed
   :
  IntoValTypedUnderlying (leakbuffer.LeakyBuffer.t) (leakbuffer.LeakyBufferⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance LeakyBuffer_access_load_serverChan l (v : (leakbuffer.LeakyBuffer.t)) dq :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "serverChan"] ↦{dq} (v.(leakbuffer.LeakyBuffer.serverChan')))
    (l.[(leakbuffer.LeakyBuffer.t), "serverChan"] ↦{dq} (v.(leakbuffer.LeakyBuffer.serverChan')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LeakyBuffer_access_store_serverChan l (v : (leakbuffer.LeakyBuffer.t)) serverChan' :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "serverChan"] ↦ (v.(leakbuffer.LeakyBuffer.serverChan')))
    (l.[(leakbuffer.LeakyBuffer.t), "serverChan"] ↦ serverChan')
    (l ↦ v) (l ↦ (v <|(leakbuffer.LeakyBuffer.serverChan') := serverChan'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance LeakyBuffer_access_load_free l (v : (leakbuffer.LeakyBuffer.t)) dq :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "free"] ↦{dq} (v.(leakbuffer.LeakyBuffer.free')))
    (l.[(leakbuffer.LeakyBuffer.t), "free"] ↦{dq} (v.(leakbuffer.LeakyBuffer.free')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LeakyBuffer_access_store_free l (v : (leakbuffer.LeakyBuffer.t)) free' :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "free"] ↦ (v.(leakbuffer.LeakyBuffer.free')))
    (l.[(leakbuffer.LeakyBuffer.t), "free"] ↦ free')
    (l ↦ v) (l ↦ (v <|(leakbuffer.LeakyBuffer.free') := free'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance LeakyBuffer_access_load_bufCap l (v : (leakbuffer.LeakyBuffer.t)) dq :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "bufCap"] ↦{dq} (v.(leakbuffer.LeakyBuffer.bufCap')))
    (l.[(leakbuffer.LeakyBuffer.t), "bufCap"] ↦{dq} (v.(leakbuffer.LeakyBuffer.bufCap')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance LeakyBuffer_access_store_bufCap l (v : (leakbuffer.LeakyBuffer.t)) bufCap' :
  AccessStrict
    (l.[(leakbuffer.LeakyBuffer.t), "bufCap"] ↦ (v.(leakbuffer.LeakyBuffer.bufCap')))
    (l.[(leakbuffer.LeakyBuffer.t), "bufCap"] ↦ bufCap')
    (l ↦ v) (l ↦ (v <|(leakbuffer.LeakyBuffer.bufCap') := bufCap'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End LeakyBuffer.

End leakbuffer.
