(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.bytes.
Require Export New.generatedproof.encoding.binary.
Require Export New.golang.theory.
Require Export New.code.github_com.goose_lang.goose.testdata.examples.channel.map_reduce.records.

Set Default Proof Using "Type".

Module records.
Module WordCountCodec.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : records.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance WordCountCodec_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (records.WordCountCodec.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance WordCountCodec_into_val_typed
   :
  IntoValTypedUnderlying (records.WordCountCodec.t) (records.WordCountCodecⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.

End def.
End WordCountCodec.

End records.
