(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.goose.testdata.examples.channel.map_reduce.records.
Require Export New.generatedproof.slices.
Require Export New.golang.theory.
Require Export New.code.github_com.goose_lang.goose.testdata.examples.channel.map_reduce.ring_buff.

Set Default Proof Using "Type".

Module ring.
Module RingBuffer.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : ring.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance RingBuffer_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (ring.RingBuffer.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "data" ∷ l.[(ring.RingBuffer.t), "data"] ↦{dq} v.(ring.RingBuffer.data') ∗
      "free" ∷ l.[(ring.RingBuffer.t), "free"] ↦{dq} v.(ring.RingBuffer.free') ∗
      "slotCap" ∷ l.[(ring.RingBuffer.t), "slotCap"] ↦{dq} v.(ring.RingBuffer.slotCap') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance RingBuffer_into_val_typed
   :
  IntoValTypedUnderlying (ring.RingBuffer.t) (ring.RingBufferⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance RingBuffer_access_load_data l (v : (ring.RingBuffer.t)) dq :
  AccessStrict
    (l.[(ring.RingBuffer.t), "data"] ↦{dq} (v.(ring.RingBuffer.data')))
    (l.[(ring.RingBuffer.t), "data"] ↦{dq} (v.(ring.RingBuffer.data')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance RingBuffer_access_store_data l (v : (ring.RingBuffer.t)) data' :
  AccessStrict
    (l.[(ring.RingBuffer.t), "data"] ↦ (v.(ring.RingBuffer.data')))
    (l.[(ring.RingBuffer.t), "data"] ↦ data')
    (l ↦ v) (l ↦ (v <|(ring.RingBuffer.data') := data'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance RingBuffer_access_load_free l (v : (ring.RingBuffer.t)) dq :
  AccessStrict
    (l.[(ring.RingBuffer.t), "free"] ↦{dq} (v.(ring.RingBuffer.free')))
    (l.[(ring.RingBuffer.t), "free"] ↦{dq} (v.(ring.RingBuffer.free')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance RingBuffer_access_store_free l (v : (ring.RingBuffer.t)) free' :
  AccessStrict
    (l.[(ring.RingBuffer.t), "free"] ↦ (v.(ring.RingBuffer.free')))
    (l.[(ring.RingBuffer.t), "free"] ↦ free')
    (l ↦ v) (l ↦ (v <|(ring.RingBuffer.free') := free'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance RingBuffer_access_load_slotCap l (v : (ring.RingBuffer.t)) dq :
  AccessStrict
    (l.[(ring.RingBuffer.t), "slotCap"] ↦{dq} (v.(ring.RingBuffer.slotCap')))
    (l.[(ring.RingBuffer.t), "slotCap"] ↦{dq} (v.(ring.RingBuffer.slotCap')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance RingBuffer_access_store_slotCap l (v : (ring.RingBuffer.t)) slotCap' :
  AccessStrict
    (l.[(ring.RingBuffer.t), "slotCap"] ↦ (v.(ring.RingBuffer.slotCap')))
    (l.[(ring.RingBuffer.t), "slotCap"] ↦ slotCap')
    (l ↦ v) (l ↦ (v <|(ring.RingBuffer.slotCap') := slotCap'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End RingBuffer.

Module Run.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : ring.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Run_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (ring.Run.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Refs" ∷ l.[(ring.Run.t), "Refs"] ↦{dq} v.(ring.Run.Refs') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Run_into_val_typed
   :
  IntoValTypedUnderlying (ring.Run.t) (ring.Runⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Run_access_load_Refs l (v : (ring.Run.t)) dq :
  AccessStrict
    (l.[(ring.Run.t), "Refs"] ↦{dq} (v.(ring.Run.Refs')))
    (l.[(ring.Run.t), "Refs"] ↦{dq} (v.(ring.Run.Refs')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Run_access_store_Refs l (v : (ring.Run.t)) Refs' :
  AccessStrict
    (l.[(ring.Run.t), "Refs"] ↦ (v.(ring.Run.Refs')))
    (l.[(ring.Run.t), "Refs"] ↦ Refs')
    (l ↦ v) (l ↦ (v <|(ring.Run.Refs') := Refs'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Run.

Module Ref.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : ring.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Ref_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (ring.Ref.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Partition" ∷ l.[(ring.Ref.t), "Partition"] ↦{dq} v.(ring.Ref.Partition') ∗
      "Data" ∷ l.[(ring.Ref.t), "Data"] ↦{dq} v.(ring.Ref.Data') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Ref_into_val_typed
   :
  IntoValTypedUnderlying (ring.Ref.t) (ring.Refⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Ref_access_load_Partition l (v : (ring.Ref.t)) dq :
  AccessStrict
    (l.[(ring.Ref.t), "Partition"] ↦{dq} (v.(ring.Ref.Partition')))
    (l.[(ring.Ref.t), "Partition"] ↦{dq} (v.(ring.Ref.Partition')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Ref_access_store_Partition l (v : (ring.Ref.t)) Partition' :
  AccessStrict
    (l.[(ring.Ref.t), "Partition"] ↦ (v.(ring.Ref.Partition')))
    (l.[(ring.Ref.t), "Partition"] ↦ Partition')
    (l ↦ v) (l ↦ (v <|(ring.Ref.Partition') := Partition'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Ref_access_load_Data l (v : (ring.Ref.t)) dq :
  AccessStrict
    (l.[(ring.Ref.t), "Data"] ↦{dq} (v.(ring.Ref.Data')))
    (l.[(ring.Ref.t), "Data"] ↦{dq} (v.(ring.Ref.Data')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Ref_access_store_Data l (v : (ring.Ref.t)) Data' :
  AccessStrict
    (l.[(ring.Ref.t), "Data"] ↦ (v.(ring.Ref.Data')))
    (l.[(ring.Ref.t), "Data"] ↦ Data')
    (l ↦ v) (l ↦ (v <|(ring.Ref.Data') := Data'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Ref.

Module Slot.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : ring.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Slot_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (ring.Slot.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Data" ∷ l.[(ring.Slot.t), "Data"] ↦{dq} v.(ring.Slot.Data') ∗
      "End" ∷ l.[(ring.Slot.t), "End"] ↦{dq} v.(ring.Slot.End') ∗
      "Sidecar" ∷ l.[(ring.Slot.t), "Sidecar"] ↦{dq} v.(ring.Slot.Sidecar') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Slot_into_val_typed
   :
  IntoValTypedUnderlying (ring.Slot.t) (ring.Slotⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Slot_access_load_Data l (v : (ring.Slot.t)) dq :
  AccessStrict
    (l.[(ring.Slot.t), "Data"] ↦{dq} (v.(ring.Slot.Data')))
    (l.[(ring.Slot.t), "Data"] ↦{dq} (v.(ring.Slot.Data')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Slot_access_store_Data l (v : (ring.Slot.t)) Data' :
  AccessStrict
    (l.[(ring.Slot.t), "Data"] ↦ (v.(ring.Slot.Data')))
    (l.[(ring.Slot.t), "Data"] ↦ Data')
    (l ↦ v) (l ↦ (v <|(ring.Slot.Data') := Data'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Slot_access_load_End l (v : (ring.Slot.t)) dq :
  AccessStrict
    (l.[(ring.Slot.t), "End"] ↦{dq} (v.(ring.Slot.End')))
    (l.[(ring.Slot.t), "End"] ↦{dq} (v.(ring.Slot.End')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Slot_access_store_End l (v : (ring.Slot.t)) End' :
  AccessStrict
    (l.[(ring.Slot.t), "End"] ↦ (v.(ring.Slot.End')))
    (l.[(ring.Slot.t), "End"] ↦ End')
    (l ↦ v) (l ↦ (v <|(ring.Slot.End') := End'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Slot_access_load_Sidecar l (v : (ring.Slot.t)) dq :
  AccessStrict
    (l.[(ring.Slot.t), "Sidecar"] ↦{dq} (v.(ring.Slot.Sidecar')))
    (l.[(ring.Slot.t), "Sidecar"] ↦{dq} (v.(ring.Slot.Sidecar')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Slot_access_store_Sidecar l (v : (ring.Slot.t)) Sidecar' :
  AccessStrict
    (l.[(ring.Slot.t), "Sidecar"] ↦ (v.(ring.Slot.Sidecar')))
    (l.[(ring.Slot.t), "Sidecar"] ↦ Sidecar')
    (l ↦ v) (l ↦ (v <|(ring.Slot.Sidecar') := Sidecar'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Slot.

End ring.
