(* autogenerated from github.com/mit-pdos/perennial/goose/testdata/examples/channel/unbounded *)
Require Export New.code.errors.
Require Export New.code.sync.
From New.golang Require Import defn.
Module pkg_id.
Definition unbounded : go_string := "github.com/mit-pdos/perennial/goose/testdata/examples/channel/unbounded".

End pkg_id.
Export pkg_id.
Module unbounded.

Definition Unbounded {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/mit-pdos/perennial/goose/testdata/examples/channel/unbounded.Unbounded"%go [].

#[global] Opaque Unbounded.

Definition errBufferClosed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/mit-pdos/perennial/goose/testdata/examples/channel/unbounded.errBufferClosed"%go.

Definition NewUnbounded {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/mit-pdos/perennial/goose/testdata/examples/channel/unbounded.NewUnbounded"%go.

(* NewUnbounded returns a new instance of Unbounded.

   go: unbounded.go:48:6 *)
Definition NewUnboundedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (GoAlloc Unbounded (let: "$v0" := ((FuncResolve go.make2 [go.ChannelType go.sendrecv go.any] #()) #(W64 1)) in
     CompositeLiteral Unbounded (LiteralValue [KeyedElement (Some (KeyField "c"%go)) (ElementExpression (go.ChannelType go.sendrecv go.any) "$v0")])))).

(* Put adds t to the unbounded buffer.

   go: unbounded.go:55:21 *)
Definition Unbounded__Putⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "b" "t",
    with_defer: (let: "b" := (GoAlloc (go.PointerType Unbounded) "b") in
    let: "t" := (GoAlloc go.any "t") in
    do:  ((MethodResolve (go.PointerType sync.Mutex) "Lock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) #());;;
    do:  (let: "$f" := (MethodResolve (go.PointerType sync.Mutex) "Unlock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) in
    "$defer" <-[deferType] (let: "$oldf" := (![deferType] "$defer") in
    (λ: <>,
      "$f" #();;
      "$oldf" #()
      )));;;
    (if: ![go.bool] (StructFieldRef Unbounded "closing"%go (![go.PointerType Unbounded] "b"))
    then return: (![go.error] (GlobalVarAddr errBufferClosed #()))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))) in
    (FuncResolve go.len [go.SliceType go.any] #()) "$a0") =⟨go.int⟩ #(W64 0))
    then
      let: "$v0" := (![go.any] "t") in
      let: "$ch0" := (![go.ChannelType go.sendrecv go.any] (StructFieldRef Unbounded "c"%go (![go.PointerType Unbounded] "b"))) in
      SelectStmt (SelectStmtClauses (Some (do:  #())) [(CommClause (SendCase go.any "$ch0" "$v0") (return: (Convert go.untyped_nil go.error UntypedNil)))])
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))) in
    let: "$a1" := ((let: "$sl0" := (![go.any] "t") in
    CompositeLiteral (go.SliceType go.any) (LiteralValue [KeyedElement None (ElementExpression go.any "$sl0")]))) in
    (FuncResolve go.append [go.SliceType go.any] #()) "$a0" "$a1") in
    do:  ((StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b")) <-[go.SliceType go.any] "$r0");;;
    return: (Convert go.untyped_nil go.error UntypedNil)).

(* Load sends the earliest buffered data, if any, onto the read channel returned
   by Get(). Users are expected to call this every time they successfully read a
   value from the read channel.

   go: unbounded.go:75:21 *)
Definition Unbounded__Loadⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "b" <>,
    with_defer: (let: "b" := (GoAlloc (go.PointerType Unbounded) "b") in
    do:  ((MethodResolve (go.PointerType sync.Mutex) "Lock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) #());;;
    do:  (let: "$f" := (MethodResolve (go.PointerType sync.Mutex) "Unlock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) in
    "$defer" <-[deferType] (let: "$oldf" := (![deferType] "$defer") in
    (λ: <>,
      "$f" #();;
      "$oldf" #()
      )));;;
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))) in
    (FuncResolve go.len [go.SliceType go.any] #()) "$a0") >⟨go.int⟩ #(W64 0))
    then
      let: "$v0" := (![go.any] (IndexRef (go.SliceType go.any) (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b")), #(W64 0)))) in
      let: "$ch0" := (![go.ChannelType go.sendrecv go.any] (StructFieldRef Unbounded "c"%go (![go.PointerType Unbounded] "b"))) in
      SelectStmt (SelectStmtClauses (Some (do:  #())) [(CommClause (SendCase go.any "$ch0" "$v0") (let: "$r0" := (Convert go.untyped_nil go.any UntypedNil) in
      do:  ((IndexRef (go.SliceType go.any) (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b")), #(W64 0))) <-[go.any] "$r0");;;
      let: "$r0" := (let: "$s" := (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))) in
      Slice (go.SliceType go.any) ("$s", #(W64 1), FuncResolve go.len [go.SliceType go.any] #() (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))))) in
      do:  ((StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b")) <-[go.SliceType go.any] "$r0")))])
    else
      (if: (![go.bool] (StructFieldRef Unbounded "closing"%go (![go.PointerType Unbounded] "b"))) && (⟨go.bool⟩! (![go.bool] (StructFieldRef Unbounded "closed"%go (![go.PointerType Unbounded] "b"))))
      then
        let: "$r0" := #true in
        do:  ((StructFieldRef Unbounded "closed"%go (![go.PointerType Unbounded] "b")) <-[go.bool] "$r0");;;
        do:  (let: "$a0" := (![go.ChannelType go.sendrecv go.any] (StructFieldRef Unbounded "c"%go (![go.PointerType Unbounded] "b"))) in
        (FuncResolve go.close [go.ChannelType go.sendrecv go.any] #()) "$a0")
      else do:  #()));;;
    return: #()).

(* Get returns a read channel on which values added to the buffer, via Put(),
   are sent on.

   Upon reading a value from this channel, users are expected to call Load() to
   send the next buffered value onto the channel if there is any.

   If the unbounded buffer is closed, the read channel returned by this method
   is closed after all data is drained.

   go: unbounded.go:99:21 *)
Definition Unbounded__Getⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "b" <>,
    exception_do (let: "b" := (GoAlloc (go.PointerType Unbounded) "b") in
    return: (Convert (go.ChannelType go.sendrecv go.any) (go.ChannelType go.recvonly go.any) (![go.ChannelType go.sendrecv go.any] (StructFieldRef Unbounded "c"%go (![go.PointerType Unbounded] "b"))))).

(* Close closes the unbounded buffer. No subsequent data may be Put(), and the
   channel returned from Get() will be closed after all the data is read and
   Load() is called for the final time.

   go: unbounded.go:106:21 *)
Definition Unbounded__Closeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "b" <>,
    with_defer: (let: "b" := (GoAlloc (go.PointerType Unbounded) "b") in
    do:  ((MethodResolve (go.PointerType sync.Mutex) "Lock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) #());;;
    do:  (let: "$f" := (MethodResolve (go.PointerType sync.Mutex) "Unlock"%go (StructFieldRef Unbounded "mu"%go (![go.PointerType Unbounded] "b"))) in
    "$defer" <-[deferType] (let: "$oldf" := (![deferType] "$defer") in
    (λ: <>,
      "$f" #();;
      "$oldf" #()
      )));;;
    (if: ![go.bool] (StructFieldRef Unbounded "closing"%go (![go.PointerType Unbounded] "b"))
    then return: (#())
    else do:  #());;;
    let: "$r0" := #true in
    do:  ((StructFieldRef Unbounded "closing"%go (![go.PointerType Unbounded] "b")) <-[go.bool] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((let: "$a0" := (![go.SliceType go.any] (StructFieldRef Unbounded "backlog"%go (![go.PointerType Unbounded] "b"))) in
    (FuncResolve go.len [go.SliceType go.any] #()) "$a0") =⟨go.int⟩ #(W64 0))
    then
      let: "$r0" := #true in
      do:  ((StructFieldRef Unbounded "closed"%go (![go.PointerType Unbounded] "b")) <-[go.bool] "$r0");;;
      do:  (let: "$a0" := (![go.ChannelType go.sendrecv go.any] (StructFieldRef Unbounded "c"%go (![go.PointerType Unbounded] "b"))) in
      (FuncResolve go.close [go.ChannelType go.sendrecv go.any] #()) "$a0")
    else do:  #());;;
    return: #()).

#[global] Instance info' : PkgInfo pkg_id.unbounded :=
{|
  pkg_imported_pkgs := [code.errors.pkg_id.errors; code.sync.pkg_id.sync]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.unbounded (λ: <>,
      exception_do (do:  (go.GlobalAlloc errBufferClosed go.error #());;;
      do:  (sync.initialize' #());;;
      do:  (errors.initialize' #());;;
      let: "$r0" := (let: "$a0" := #"Put called on closed buffer.Unbounded"%go in
      (FuncResolve errors.New [] #()) "$a0") in
      do:  ((GlobalVarAddr errBufferClosed #()) <-[go.error] "$r0"))
      ).

Module Unbounded.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  c' : chan.t;
  closed' : bool;
  closing' : bool;
  mu' : sync.Mutex.t;
  backlog' : slice.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Unbounded.

Definition Unbounded'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "c"%go (go.ChannelType go.sendrecv go.any));
  (go.FieldDecl "closed"%go go.bool);
  (go.FieldDecl "closing"%go go.bool);
  (go.FieldDecl "mu"%go sync.Mutex);
  (go.FieldDecl "backlog"%go (go.SliceType go.any))
].
Program Definition Unbounded'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Unbounded'fds_unsealed).
Global Instance equals_unfold_Unbounded {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Unbounded'fds =→ Unbounded'fds_unsealed.
Proof. rewrite /Unbounded'fds seal_eq //. Qed.

Definition Unboundedⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Unbounded'fds).

Class Unbounded_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Unbounded_type_repr  :: go.TypeReprUnderlying Unboundedⁱᵐᵖˡ Unbounded.t;
  #[global] Unbounded_underlying :: (Unbounded) <u (Unboundedⁱᵐᵖˡ);
  #[global] Unbounded_get_c (x : Unbounded.t) :: ⟦StructFieldGet (Unboundedⁱᵐᵖˡ) "c", #x⟧ ⤳[under] #x.(Unbounded.c');
  #[global] Unbounded_set_c (x : Unbounded.t) y :: ⟦StructFieldSet (Unboundedⁱᵐᵖˡ) "c", (#x, #y)⟧ ⤳[under] #(x <|Unbounded.c' := y|>);
  #[global] Unbounded_get_closed (x : Unbounded.t) :: ⟦StructFieldGet (Unboundedⁱᵐᵖˡ) "closed", #x⟧ ⤳[under] #x.(Unbounded.closed');
  #[global] Unbounded_set_closed (x : Unbounded.t) y :: ⟦StructFieldSet (Unboundedⁱᵐᵖˡ) "closed", (#x, #y)⟧ ⤳[under] #(x <|Unbounded.closed' := y|>);
  #[global] Unbounded_get_closing (x : Unbounded.t) :: ⟦StructFieldGet (Unboundedⁱᵐᵖˡ) "closing", #x⟧ ⤳[under] #x.(Unbounded.closing');
  #[global] Unbounded_set_closing (x : Unbounded.t) y :: ⟦StructFieldSet (Unboundedⁱᵐᵖˡ) "closing", (#x, #y)⟧ ⤳[under] #(x <|Unbounded.closing' := y|>);
  #[global] Unbounded_get_mu (x : Unbounded.t) :: ⟦StructFieldGet (Unboundedⁱᵐᵖˡ) "mu", #x⟧ ⤳[under] #x.(Unbounded.mu');
  #[global] Unbounded_set_mu (x : Unbounded.t) y :: ⟦StructFieldSet (Unboundedⁱᵐᵖˡ) "mu", (#x, #y)⟧ ⤳[under] #(x <|Unbounded.mu' := y|>);
  #[global] Unbounded_get_backlog (x : Unbounded.t) :: ⟦StructFieldGet (Unboundedⁱᵐᵖˡ) "backlog", #x⟧ ⤳[under] #x.(Unbounded.backlog');
  #[global] Unbounded_set_backlog (x : Unbounded.t) y :: ⟦StructFieldSet (Unboundedⁱᵐᵖˡ) "backlog", (#x, #y)⟧ ⤳[under] #(x <|Unbounded.backlog' := y|>);
  #[global] Unbounded'ptr_Close_unfold :: MethodUnfold (go.PointerType (Unbounded)) "Close" (Unbounded__Closeⁱᵐᵖˡ);
  #[global] Unbounded'ptr_Get_unfold :: MethodUnfold (go.PointerType (Unbounded)) "Get" (Unbounded__Getⁱᵐᵖˡ);
  #[global] Unbounded'ptr_Load_unfold :: MethodUnfold (go.PointerType (Unbounded)) "Load" (Unbounded__Loadⁱᵐᵖˡ);
  #[global] Unbounded'ptr_Put_unfold :: MethodUnfold (go.PointerType (Unbounded)) "Put" (Unbounded__Putⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Unbounded_instance :: Unbounded_Assumptions;
  #[global] NewUnbounded_unfold :: FuncUnfold NewUnbounded [] (NewUnboundedⁱᵐᵖˡ);
  #[global] import_errors_Assumption :: errors.Assumptions;
  #[global] import_sync_Assumption :: sync.Assumptions;
}.
End unbounded.
